language: ruby
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
deploy:
  provider: heroku
  api_key:
    secure: WE3Ye4Fg3KnOU/JsczcqWnxDBP1FXORHiBASBv7uX2yt3psd4fSVuqC8llGKV+y0OIr3QKRwbs9siETmClkXQVpfjxnpBO5Z6BSxpvYtUwEtSTWSftenXOd+Qf/+BrC7EPHoYs5RKV1qpJ7PiBaj53TTktcRFu8ZEaB5qYMWh4Y=
  app: give-up-less
  on:
    repo: developers-cut/give-up-less
